### ISSUE TITLE
hey there. win32 support

### ISSUE THREAD

**Issue by r-lyeh-archived** [skeeto/interactive-c-demo#3]
hey don, long time no see : )
hope you're doing well. would you be interested in a working win32 port? if so, should i PR it ?

**Comment by skeeto** [comment]
Sure, I guess. I'd rather avoid #ifdef spaghetti, especially since this
is primarily an educational demo, so I'd like to keep the port in a
separate branch or in a separate main.c (main_win32.c?). I hope game.c
doesn't need to be changed, but I'm not sure how well that malloc()
allocation will be handled across reloads on Windows.

**Comment by r-lyeh-archived** [comment]
sent you a PR. changes are tiny so i dont think they need a different branch after all

**Comment by r-lyeh-archived** [comment]
i updated the PR because I forgot to reference this issue : )  no other changes were performed
